# Generated by Django 3.2.10 on 2021-12-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], max_length=25)),
                ('file', models.FileField(upload_to='files/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
        ),
    ]
